myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name='list'),
    path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>/', views.posts_page, name='page'), # example url: /my-first-post/
]

myproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

myproject/posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField(max_length=75) # example slug: my-first-post
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=None)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'slug': self.slug})

myproject/users/models.py
from django.db import models

# Create your models here.

myproject/myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    # return HttpResponse('Hello, Home page!')
    return render(request, 'home.html')

def about(request):
    # return HttpResponse('About us')
    return render(request, 'about.html')

myproject/posts/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Post
from django.contrib.auth.decorators import login_required
from .form import CreateForm

# Create your views here.
def posts_list(request):
    # Displaying Posts with Template Tags
    posts = Post.objects.all()
    return render(request, 'posts/post_list.html', {'posts': posts})

def posts_page(request, slug):
    post = Post.objects.get(slug=slug)
    if post is None:
        return HttpResponse('Post not found', status=404)
    return render(request, 'posts/post_page.html', {'post': post})

@login_required(login_url='/users/login')
def post_new(request):
    if request.method == 'POST':
        form = CreateForm(request.POST, request.FILES)
        if form.is_valid():
            # Save with user
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:list')
    else:
        form = CreateForm()
    return render(request, 'posts/post_new.html', {'form': form})

myproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:list')
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('posts:list')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('posts:list')

myproject/posts/templates/posts/post_list.html
{% extends 'layout.html' %}

{% block title %}
POST LIST 📃
{% endblock %}

{% block content %}
<section>
    <h1>POST LIST 📃</h1>

    {% for post in posts %}
    <article>
        <h2>
            <a href="{% url 'posts:page' post.slug %}">{{ post.title }}</a>
        </h2>
        <p>{{ post.body }}</p>
        <p>{{ post.date }} by {{ post.author }}</p>
        <hr>
    </article>
    {% endfor %}
</section>
{% endblock %}

myproject/posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
NEW POST 📝
{% endblock %}

{% block content %}
<section>
    <h1>NEW POST 📝</h1>
    <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit" type="submit">Create</button>
    </form>
</section>
{% endblock %}

myproject/posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
<section>
    <section>
        <img class="banner" src="{{ post.banner.url }}" alt="{{ post.title }}"/>
        <h2>
            <a href="{% url 'posts:page' post.slug %}">{{ post.title }}</a>
        </h2>
        <p>{{ post.body }}</p>
        <p>{{ post.date }}</p>
        <hr>
    </section>
</section>
{% endblock %}

myproject/templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About page ℹ️
{% endblock %}

{% block content %}
    <h1>About page</h1>
    <p>Check out my <a href="/">Home Page</a></p>
{% endblock %}

myproject/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home page 🏠
{% endblock %}

{% block content %}
    <h1>Home page</h1>
    <p>Check out my <a href="/about">About Page</a></p>
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/">Home</a>
        <a href="/about">About</a>
        <a href="{% url 'posts:list' %}">Posts</a>
        {% if user.is_authenticated %}
            <a href="{% url 'posts:new-post' %}">New Post</a>
            <form action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
        {% endif %}
        {% if not user.is_authenticated %}
            <a href="{% url 'users:register' %}">Register</a>
            <a href="{% url 'users:login' %}">Login</a>
        {% endif %}
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

myproject/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
Login
{% endblock %}

{% block content %}
<section>
    <h1>Login to your account</h1>
    <form class="form-with-validation" action="/users/login/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit" type="submit">Login</button>
    </form>
</section>
{% endblock %}

myproject/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
Register
{% endblock %}

{% block content %}
<section>
    <h1>Register a new account</h1>
    <form class="form-with-validation" action="/users/register/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit" type="submit">Register</button>
    </form>
</section>
{% endblock %}